services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - /Users/pramodvadiraja/.ollama/:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage

  mcp:
    build:
      context: mcp
    ports:
      - 9000:9000
    volumes:
      - ./utils/:/mcp/utils/

  api:
    build:
      context: api
    ports:
      - 8000:8000
    volumes:
      - ./utils/:/api/utils/
